---

name: Global Jobs

on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches:
      - 'main'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  gh-super-linter:
    name: 'GitHub Super-Linter'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Super Linter'
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_EDITORCONFIG: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_TERRAFORM_TERRASCAN: false

  terraform_lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ministryofjustice/hmpps-ems-devcontainer
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: "Terragrunt hclfmt check"
        run: terragrunt hclfmt --terragrunt-check

      - name: "Terraform fmt check"
        run: terraform fmt -check -recursive

  terraform_validate:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ministryofjustice/hmpps-ems-devcontainer
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: List all modules
        run: 
          ls modules | jq -R -s -c 'split("\n")[:-1]') | while read MODULE; do
            terrafom init -backend=false
            terraform validate
          done
