---

name: Global Jobs

on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches:
      - 'main'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  gh-super-linter:
    name: 'GitHub Super-Linter'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Super Linter'
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_EDITORCONFIG: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_TERRAFORM_TERRASCAN: false

  tf-fmt:
    name: 'Terraform Format Checks'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: Terragrunt fmt
        run: |
          echo "Updated files: ${{ steps.files.outputs.all }}"
          updated_files=''
          filtered_files=$(echo ${{ steps.files.outputs.all }} | tr -s [:space:] | tr -s [:space:] "\n" | grep ^terragrunt/)
          if [[ ! -z $filtered_files ]]; then
            updated_files=$(terragrunt/src/terraform-fmt.sh ${filtered_files})
          fi
          echo "Formatted files: ${updated_files}"
          echo ::set-output name=updated_files::${updated_files}
