---

name: Global jobs

on:
  pull_request:
    paths:
      - modules/**
    branches:
      - main

env:
    terraform_version: '0.13.3'
    terragrunt_version: 'v0.25.1'
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  triage:
    name: Global pull request jobs
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint changed files
        uses: docker://github/super-linter:latest
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_TERRAFORM_TERRASCAN: false
          VALIDATE_PYTHON_FLAKE8: false
          DEFAULT_BRANCH: main

      - name: 'Setup Terragrunt'
        uses: ministryofjustice/setup-terragrunt@v0.1.0
        with:
          terraform_version: ${{ env.terraform_version }}
          terragrunt_version: ${{ env.terragrunt_version }}

      - name: 'Terragrunt hclfmt check'
        run: ${GITHUB_WORKSPACE}/github-bin/terragrunt hclfmt --terragrunt-check

      - name: 'Terraform fmt check'
        run: ${GITHUB_WORKSPACE}/github-bin/terraform fmt -check -recursive
