---
name: Release

on:
  push:
    tags:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-release:
    name: 'Create Release'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v2

      - name: 'Create GitHub Release'
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: HMPPS EMS Terraform Modules Release ${{ github.ref }}
          body: |
            ${{ github.ref }}
          draft: false
          prerelease: false
